### ISSUE TITLE
Drop Active: true/false overlay flickering or flashing 

### ISSUE THREAD

**Issue by TheGlenn88** [lian-yue/vue-upload-component#314]
Adding a file in certain conditions makes the drop overlay flash as the gif shows.

From a Mac you can reproduce this by adding a file from finder, then adding a file from the downloads bin.

on windows you can reproduce this by adding an invalid file type, then adding an acceptable file type.

![2019-07-22 12 32 39](https://user-images.githubusercontent.com/5333026/61632394-aa0ab600-ac84-11e9-99c3-e370292cb3a1.gif)

**Comment by cvn** [comment]
I had the same issue. Maddening. I just figured it out.

It happens when `<body>` is shorter than the window and you drag over the bottom of the page.

It can be fixed with CSS:

```css
body {
  min-height: 100vh; /* prevent vue-upload-component overlay flickering */
}
```
